### ISSUE TITLE
make manual easy to import 

### ISSUE THREAD

**Issue by s72785** [RadicalMilitantLibrary/manual#8]
Right now each change on the manual would need a complete re-editing to import in the RML.
This could be a good example on how to write a book and make it available easily as the current output formats are already quite nice; just odd it does not appear on the library itself.

* Maybe replace styles in final ODT, or
* Maybe a template for `pandoc`

**Comment by ewa4boeker** [comment]
interesting idea, but I do not see this happen in nearby future.

**Comment by vv01f** [comment]
well, likely [www#8](https://github.com/RadicalMilitantLibrary/www/issues/8) solves this

**Comment by ewa4boeker** [comment]
Mh, I favor editing/updating books in case over this one. as in: this will not happen on the manual part.
